package com.example.cegct.features.auth.ui

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    CHICHEWA("ny", "Chichewa")
}

data class AuthStrings(
    val appTitle: String = "CEGCT",
    val appTagline: String = "Community Engagement & Governance Citizen Tool",
    val welcomeTitle: String = "Welcome",
    val login: String = "Log in",
    val createAccount: String = "Create account",
    val continueAnonymously: String = "Continue anonymously",
    val languageLabel: String = "Language",
    val loginHeaderTitle: String = "Welcome Back",
    val loginHeaderSubtitle: String = "Log in to your citizen account",
    val emailLabel: String = "Email",
    val passwordLabel: String = "Password",
    val forgotPasswordLink: String = "Forgot password?",
    val continueWithGoogle: String = "Continue with Google",
    val registerHeaderTitle: String = "Create Account",
    val registerHeaderSubtitle: String = "Sign up to start reporting community issues",
    val fullNameLabel: String = "Full Name",
    val phoneNumberLabel: String = "Phone Number",
    val confirmPasswordLabel: String = "Confirm Password",
    val passwordStrengthLabel: String = "Password Strength",
    val weak: String = "Weak",
    val medium: String = "Medium",
    val good: String = "Good",
    val strong: String = "Strong",
    val agreeTermsPrefix: String = "I agree to the ",
    val termsOfService: String = "Terms of Service",
    val and: String = " and ",
    val privacyPolicy: String = "Privacy Policy",
    val identityProtectionNotice: String = "Learn how reporter identities are protected",
    val verifyHeaderTitle: String = "Verify Email",
    val verifyHeaderSubtitle: String = "We sent a 6-digit code to",
    val changeEmail: String = "Change email",
    val resendCodeIn: String = "Resend code in %ds",
    val resendCode: String = "Resend Code",
    val verifyButton: String = "Verify Email",
    val genericAuthError: String = "Email or password is incorrect",
    val errValidEmail: String = "Enter a valid email address",
    val errValidPhone: String = "Enter a valid phone number",
    val errFullNameRequired: String = "Full name is required",
    val errPasswordLength: String = "Password must be at least 8 characters",
    val errPasswordMismatch: String = "Passwords do not match",
    val errTermsRequired: String = "You must agree to the Terms & Privacy Policy to proceed"
)

fun getAuthStrings(language: AppLanguage): AuthStrings {
    return when (language) {
        AppLanguage.ENGLISH -> AuthStrings()
        AppLanguage.CHICHEWA -> AuthStrings(
            appTitle = "CEGCT",
            appTagline = "Zida Zotengapo Mbali ndi Ulamuliro wa Nzika",
            welcomeTitle = "Takulandirani",
            login = "Lowa",
            createAccount = "Panga akaunti",
            continueAnonymously = "Pitirizani popanda akaunti",
            languageLabel = "Chilankhulo",
            loginHeaderTitle = "Takulandiraninso",
            loginHeaderSubtitle = "Lowa mu akaunti yanu ya nzika",
            emailLabel = "Imelo",
            passwordLabel = "Chinsinsi",
            forgotPasswordLink = "Mwaiwala chinsinsi?",
            continueWithGoogle = "Pitirizani ndi Google",
            registerHeaderTitle = "Panga Akaunti",
            registerHeaderSubtitle = "Lembetsani kuti muyambe kupereka lipoti la m'dera lanu",
            fullNameLabel = "Dzina Lense",
            phoneNumberLabel = "Nambala ya Foni",
            confirmPasswordLabel = "Tsimikizani Chinsinsi",
            passwordStrengthLabel = "Mphamvu ya Chinsinsi",
            weak = "Wofooka",
            medium = "Pakatikati",
            good = "Wabwino",
            strong = "Wamphamvu",
            agreeTermsPrefix = "Ndikuvomereza ",
            termsOfService = "Migwirizano ya Ntchito",
            and = " ndi ",
            privacyPolicy = "Mfundo za Chinsinsi",
            identityProtectionNotice = "Dziwani momwe chidziwitso cha wopereka lipoti chimasungidwira",
            verifyHeaderTitle = "Tsimikizani Imelo",
            verifyHeaderSubtitle = "Tatumiza khodi ya manambala 6 ku",
            changeEmail = "Sinthani imelo",
            resendCodeIn = "Tumizaninso khodi m'masekondi %d",
            resendCode = "Tumizaninso Khodi",
            verifyButton = "Tsimikizani Imelo",
            genericAuthError = "Imelo kapena chinsinsi si zolondola",
            errValidEmail = "Lembani imelo yolondola",
            errValidPhone = "Lembani nambala ya foni yolondola",
            errFullNameRequired = "Dzina lense likufunika",
            errPasswordLength = "Chinsinsi chikhale cha manambala kapena amakalata osachepera 8",
            errPasswordMismatch = "Zinsinsi sizikugwirizana",
            errTermsRequired = "Muenera kuvomereza Mfundo za Chinsinsi ndi Migwirizano kuti mupitirize"
        )
    }
}
